name: Flutter CI

on:
  push:
    branches: [release]

jobs:
  build:
    runs-on: self-hosted

    steps:
     - name: pub get packages
        run: flutter pub get

      - name: test
         run: flutter test